const DATABASE_NAME = 'reddit';
const SUBREDDITS_TABLE_TITLE = 'subreddits';
const POSTS_TABLE_TITLE = 'posts';
const COMMENTS_TABLE_TITLE = 'comments';

const SUBREDDITS_LIMIT = 100;
const POSTS_LIMIT = 100;
const INTERVAL_TO_FETCH_NEW_DATA = 950000;


const STATUS_CODE_OK = 200;
const STATUS_CODE_FAIL = 422;
const ERROR_MESSAGE_SUBREDDIT_NOT_FOUND = "Sorry, subreddit isn't found";
const ERROR_MESSAGE_SUBREDDIT_ALREADY_EXISTS = "Subreddit has been already archived";
const ERROR_MESSAGE_POSTS_NOT_FOUND = "Sorry, there are no posts of this subreddit";
const ERROR_MESSAGE_ABORT = "Request abort";

module.exports = {
    DATABASE_NAME,
    SUBREDDITS_TABLE_TITLE,
    POSTS_TABLE_TITLE,
    SUBREDDITS_LIMIT,
    POSTS_LIMIT,
    STATUS_CODE_OK,
    STATUS_CODE_FAIL,
    ERROR_MESSAGE_SUBREDDIT_NOT_FOUND,
    ERROR_MESSAGE_SUBREDDIT_ALREADY_EXISTS,
    ERROR_MESSAGE_POSTS_NOT_FOUND,
    COMMENTS_TABLE_TITLE,
    INTERVAL_TO_FETCH_NEW_DATA,
    ERROR_MESSAGE_ABORT
};
